const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbwYl68F844nND3HbNxFk93lrzYq3u6vX2bzkpGMubmtVV7ElqeJqPA-5V7f5bgwNg-iRQ/exec';
const API = location.origin.includes('5000') ? '' : 'http://127.0.0.1:5000';
const $=(s,e=document)=>e.querySelector(s); const $$=(s,e=document)=>[...e.querySelectorAll(s)];
let csrfToken='';
async function loadCsrf(){try{const r=await fetch(API+'/api/csrf-token',{credentials:'include'});const j=await r.json();csrfToken=j.csrf_token||'';$$('input[name="csrf_token"]').forEach(i=>i.value=csrfToken)}catch{csrfToken=''}}
function updateProgress(form){const req=$$('[required]',form);const done=req.filter(i=>i.type==='checkbox'?i.checked:String(i.value).trim()).length;const pct=req.length?Math.max(8,Math.round(done/req.length*100)):100;const bar=$('.progress span',form.closest('.form-shell')||document);if(bar)bar.style.width=pct+'%'}
function fillPortales(){ $$('[data-portales]').forEach(sel=>{sel.innerHTML='<option value="">Selecciona calle y portal</option>'+window.PORTALES_CASITAS.map(p=>`<option>${p}</option>`).join('')})}
function togglePortal(){ $$('[data-propietario]').forEach(r=>{const target=$(r.dataset.propietario);const yes=$$('input[name="propietario"]',r).find(x=>x.checked)?.value==='si'; if(target){target.hidden=!yes; $$('select,input',target).forEach(el=>{ if(!yes) el.value=''; });}})}
function toggleColaboracion(){const box=$('#tipos-colaboracion'); if(!box)return; const yes=$$('input[name="quiere_participar"]').find(x=>x.checked)?.value==='si'; box.hidden=!yes; if(!yes) $$('input[type="checkbox"]',box).forEach(x=>x.checked=false)}
function setupDrop(){ $$('[data-drop]').forEach(zone=>{const input=$('input[type=file]',zone), previews=$('.previews',zone);let filesList=[];zone.addEventListener('click',e=>{if(e.target===zone||e.target.closest('[data-drop-label]'))input.click()});zone.addEventListener('dragover',e=>{e.preventDefault();zone.style.background='#f2e9f7'});zone.addEventListener('dragleave',()=>zone.style.background='');zone.addEventListener('drop',e=>{e.preventDefault();filesList=[...e.dataTransfer.files];sync();render()});input.addEventListener('change',()=>{filesList=[...input.files];render()});function sync(){const dt=new DataTransfer();filesList.forEach(f=>dt.items.add(f));input.files=dt.files}function render(){previews.innerHTML='';filesList.forEach((f,i)=>{if(!f.type.startsWith('image/'))return;const wrap=document.createElement('div');wrap.className='preview-wrap';const img=document.createElement('img');img.className='preview';img.src=URL.createObjectURL(f);const btn=document.createElement('button');btn.type='button';btn.className='remove-photo';btn.textContent='×';btn.onclick=(ev)=>{ev.stopPropagation();filesList.splice(i,1);sync();render()};wrap.append(img,btn);previews.appendChild(wrap)})}})}
async function postForm(form,endpoint){const fd=new FormData(form);const datos={};for(const [k,v] of fd.entries()){if(k==='photos')continue;if(datos[k]){if(!Array.isArray(datos[k]))datos[k]=[datos[k]];datos[k].push(v);}else{datos[k]=v;}}const sig=window.getSignatureData?.();if(sig)datos.firma=sig;datos.photos=[];for(const foto of fd.getAll('photos')){if(!foto||!foto.name)continue;const b64=await fileToBase64(foto);datos.photos.push({nombre:foto.name,base64:b64});}const res=await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify(datos)});return {success:true,message:'Enviado'};}
function fileToBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});}
function bindForm(id, endpoint){const form=$(id);if(!form)return;form.addEventListener('input',()=>updateProgress(form));form.addEventListener('change',()=>{togglePortal();toggleColaboracion();updateProgress(form)});form.addEventListener('submit',async e=>{e.preventDefault();const shell=form.closest('.form-shell');const ok=$('.success',shell), err=$('.error',shell);if(err)err.textContent='';try{const data=await postForm(form,endpoint);form.reset();window.clearSignature?.();togglePortal();toggleColaboracion();updateProgress(form);if(ok){ok.textContent='Solicitud enviada correctamente.';ok.style.display='block';ok.scrollIntoView({behavior:'smooth',block:'center'})}}catch(ex){if(err)err.textContent='ERROR DETALLADO: '+(ex&&ex.message?ex.message:ex)}});updateProgress(form)}
let charts=[];function destroyCharts(){charts.forEach(c=>c.destroy());charts=[]}function chartBar(ctx, labels, values, label, horizontal=false){if(!ctx||typeof Chart==='undefined')return;charts.push(new Chart(ctx,{type:'bar',data:{labels,datasets:[{label,data:values,backgroundColor:'#a87cc4',borderRadius:10}]},options:{indexAxis:horizontal?'y':'x',responsive:true,plugins:{legend:{display:false},tooltip:{callbacks:{label:(c)=>`${c.raw}%`}}},scales:{x:{beginAtZero:true,max:horizontal?100:undefined},y:{beginAtZero:true,max:horizontal?undefined:100,ticks:{precision:0}}}}}))}
function chartDoughnut(ctx, labels, values){if(!ctx||typeof Chart==='undefined')return;charts.push(new Chart(ctx,{type:'doughnut',data:{labels,datasets:[{data:values,backgroundColor:['#a87cc4','#6c438b','#d8c5e5','#8f5ca9','#c8a6dc','#7b4aa0','#efe5f6']} ]},options:{responsive:true}}))}
function renderCharts(s){destroyCharts();chartBar($('#chart-representacion'),s.representacion_calles_labels||[],s.representacion_calles_valores||[],'Representación %',true);}
async function loadStats(){if(!$('#stats'))return;try{const r=await fetch(APPS_SCRIPT_URL+'?action=stats');const s=await r.json();$$('[data-stat]').forEach(el=>el.textContent=s[el.dataset.stat]??0);renderCharts(s);}catch(ex){console.log(ex);}}
async function loadAdmin(){const b=$('#registros-body');if(!b)return;try{const r=await fetch(API+'/api/registros',{credentials:'include'});if(r.status===401){adminStatus();return}const data=await r.json();b.innerHTML=data.map(x=>`<tr><td>${x.id}</td><td>${x.tipo}</td><td>${x.nombre}</td><td>${x.telefono}</td><td>${x.propietario||''}</td><td>${x.portal||''}</td><td>${x.quiere_participar||''}</td><td>${x.fecha_alta}</td></tr>`).join('')}catch{b.innerHTML='<tr><td colspan="8">No se han podido cargar los registros.</td></tr>'}}
async function adminStatus(){const login=$('#login-card'), panel=$('#admin-panel'), msg=$('#admin-msg'); if(!login||!panel)return; try{const r=await fetch(API+'/api/admin/status',{credentials:'include'});const s=await r.json(); if(s.authenticated){login.hidden=true;panel.hidden=false;loadStats();loadAdmin()}else{login.hidden=false;panel.hidden=true;destroyCharts()}}catch{if(msg)msg.textContent='Inicia el backend Flask para acceder al panel.'}}
function bindAdminLogin(){const form=$('#admin-login-form'); if(!form)return; form.addEventListener('submit',async e=>{e.preventDefault();const msg=$('#admin-msg'); if(msg)msg.textContent=''; const fd=new FormData(form); if(csrfToken)fd.set('csrf_token',csrfToken); try{const r=await fetch(API+'/api/admin/login',{method:'POST',body:fd,credentials:'include'}); if(r.status===400)await loadCsrf(); if(!r.ok)throw new Error(); form.reset(); await loadCsrf(); adminStatus()}catch{if(msg)msg.textContent='Usuario o contraseña incorrectos.'}}); const logout=$('#admin-logout'); if(logout)logout.addEventListener('click',async()=>{const fd=new FormData();fd.set('csrf_token',csrfToken);await fetch(API+'/api/admin/logout',{method:'POST',body:fd,credentials:'include'});await loadCsrf();adminStatus()})}
document.addEventListener('DOMContentLoaded',async()=>{await loadCsrf();fillPortales();togglePortal();toggleColaboracion();setupDrop();bindForm('#form-registro','/api/registros');bindForm('#form-barrio','/api/incidencias');bindAdminLogin();adminStatus();if(!$('#admin-panel'))loadStats()});
