window.PORTALES_CASITAS = [
  "Carrer Beat Juan Grande: 16",
  "Carrer Beat Juan Grande: 18",
  "Carrer Beat Juan Grande: 20",
  "Carrer Beat Juan Grande: 22",
  "Carrer Beat Juan Grande: 24",
  "Carrer Beat Juan Grande: 26",
  "Carrer Beat Juan Grande: 28",
  "Carrer Pare Pedro Velasco: 1",
  "Carrer Pare Pedro Velasco: 2",
  "Carrer Pare Pedro Velasco: 3",
  "Carrer Pare Pedro Velasco: 4",
  "Carrer Pare Pedro Velasco: 5",
  "Carrer Pare Pedro Velasco: 6",
  "Carrer Pare Pedro Velasco: 7",
  "Carrer Pare Pedro Velasco: 8",
  "Carrer Pare Pedro Velasco: 9",
  "Carrer Pare Pedro Velasco: 10",
  "Carrer Pare Pedro Velasco: 11",
  "Carrer Pare Pedro Velasco: 12",
  "Carrer Pare Pedro Velasco: 13",
  "Carrer Pare Antón Martín: 27",
  "Carrer Pare Antón Martín: 29",
  "Carrer Pare Antón Martín: 31",
  "Carrer Pare Antón Martín: 33",
  "Carrer Pare Antón Martín: 35",
  "Carrer Pare Antón Martín: 37",
  "Carrer Pare Antón Martín: 46",
  "Carrer Pare Antón Martín: 48",
  "Carrer Pare Antón Martín: 50",
  "Carrer Pare Antón Martín: 52",
  "Carrer Pare Antón Martín: 54",
  "Carrer Pare Antón Martín: 56",
  "Avinguda Malva-Rosa: 43",
  "Avinguda Malva-Rosa: 45",
  "Avinguda Malva-Rosa: 47",
  "Avinguda Malva-Rosa: 49",
  "Avinguda Malva-Rosa: 51",
  "Avinguda Malva-Rosa: 53",
  "Carrer Sant Rafael: 24",
  "Carrer Sant Rafael: 26",
  "Carrer Sant Rafael: 28",
  "Carrer Sant Rafael: 30",
  "Carrer Sant Rafael: 32",
  "Carrer Sant Rafael: 34",
  "Carrer Sant Joan De Déu: 25",
  "Carrer Sant Joan De Déu: 29",
  "Carrer Sant Joan De Déu: 31",
  "Carrer Sant Joan De Déu: 33",
  "Carrer Sant Joan De Déu: 35",
  "Carrer Sant Joan De Déu: 37"
];
